menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/plumaj'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/ajpm/'}

contacts:
- {name: 'Dr. Alistair Plum', 
  title: 'Postdoctoral Researcher',
  department: 'Department of Humanities', 
  institution: 'Université du Luxembourg', 
  institution_address: 'Maison Sciences Humaines, 11 Porte des Sciences, L-4366 Esch', 
  phone: '(+352) 46 66 44 4746', 
  email: 'alistair.plum@uni.lu', 
  office: 'MSH 2.152', 
  #image: 'assets/img/contact.jpg'
}
